#!/usr/bin/env node
/**
 * Starts backend server for development.
 * Tries ngrok tunnel for Expo Go; falls back to localhost if ngrok is unavailable.
 */
import { spawn, execSync } from 'node:child_process';
import fs from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
import ngrok from '@ngrok/ngrok';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

dotenv.config({ path: path.join(root, '.env.development') });

const PORT = Number(process.env.PORT || 8000);
const authtoken = process.env.NGROK_AUTHTOKEN?.trim();
const ngrokRequired = process.env.NGROK_REQUIRED === '1' || process.env.NGROK_REQUIRED === 'true';
const skipNgrok =
  process.env.SKIP_NGROK === '1' ||
  process.env.SKIP_NGROK === 'true' ||
  process.argv.includes('--local');
const ngrokEnvPath = path.join(root, '.env.ngrok.local');

function isPortInUse(port) {
  return new Promise((resolve) => {
    const tester = net.createServer();
    tester.once('error', () => resolve(true));
    tester.once('listening', () => {
      tester.close(() => resolve(false));
    });
    tester.listen(port, '0.0.0.0');
  });
}

function stopStaleNgrokProcesses() {
  if (process.platform === 'win32') {
    try {
      execSync('taskkill /F /IM ngrok.exe', { stdio: 'ignore' });
      console.log('🧹 Stopped stale ngrok.exe process(es)');
    } catch {
      /* none running */
    }
  }
}

function readCachedNgrokUrl() {
  if (!fs.existsSync(ngrokEnvPath)) return null;
  const text = fs.readFileSync(ngrokEnvPath, 'utf8');
  const match = text.match(/^NGROK_URL=(.+)$/m);
  const url = match?.[1]?.trim();
  return url || null;
}

function writeLocalEnv() {
  const localUrl = `http://localhost:${PORT}`;
  fs.writeFileSync(
    ngrokEnvPath,
    [
      '# Auto-generated by npm run dev — local fallback (no ngrok)',
      'APP_ENV=development',
      'USE_NGROK=false',
      `LOCAL_URL=${localUrl}`,
      `BASE_URL=${localUrl}`,
      `API_URL=${localUrl}/api`,
      '',
    ].join('\n'),
    'utf8',
  );
}

function writeNgrokEnv(publicUrl) {
  const localUrl = `http://localhost:${PORT}`;
  fs.writeFileSync(
    ngrokEnvPath,
    [
      '# Auto-generated by npm run dev — do not commit',
      'APP_ENV=development',
      'USE_NGROK=true',
      `LOCAL_URL=${localUrl}`,
      `NGROK_URL=${publicUrl}`,
      `BASE_URL=${publicUrl}`,
      `API_URL=${publicUrl}/api`,
      '',
    ].join('\n'),
    'utf8',
  );
}

async function cleanupNgrokSessions(cachedUrl) {
  try {
    await ngrok.kill();
  } catch {
    /* ignore */
  }
  if (cachedUrl) {
    try {
      await ngrok.disconnect(cachedUrl);
    } catch {
      /* ignore */
    }
  }
  try {
    await ngrok.disconnect();
  } catch {
    /* ignore */
  }
}

function isNgrokBusyError(message) {
  return message.includes('ERR_NGROK_334') || message.includes('already online');
}

function isNgrokNetworkError(message) {
  const lower = message.toLowerCase();
  return (
    lower.includes('failed to establish tcp connection') ||
    lower.includes('failed to connect session') ||
    lower.includes('connection reset') ||
    lower.includes('network') ||
    lower.includes('econnrefused') ||
    lower.includes('etimedout') ||
    lower.includes('offline')
  );
}

async function startNgrokListener() {
  if (!authtoken) {
    throw new Error('NGROK_AUTHTOKEN is missing in .env.development');
  }

  const cachedUrl = readCachedNgrokUrl();
  const forwardOptions = { addr: PORT, authtoken };
  const staticDomain = process.env.NGROK_DOMAIN?.trim();
  if (staticDomain) forwardOptions.domain = staticDomain;

  await cleanupNgrokSessions(cachedUrl);
  await new Promise((r) => setTimeout(r, 1000));

  try {
    return await ngrok.forward(forwardOptions);
  } catch (error) {
    const message = String(error?.message || error);
    if (!isNgrokBusyError(message)) {
      throw error;
    }

    console.log('⚠️  ngrok endpoint busy — retrying after cleanup...');
    stopStaleNgrokProcesses();
    await cleanupNgrokSessions(cachedUrl);
    await new Promise((r) => setTimeout(r, 2500));

    try {
      return await ngrok.forward(forwardOptions);
    } catch (retryError) {
      const retryMessage = String(retryError?.message || retryError);
      if (isNgrokBusyError(retryMessage) && cachedUrl) {
        console.log(`♻️  Reusing cached ngrok URL (active cloud session): ${cachedUrl}`);
        return {
          url: () => cachedUrl,
          close: async () => {},
          reused: true,
        };
      }
      throw retryError;
    }
  }
}

function printNgrokFailureHelp(errorMessage) {
  console.error('❌ Failed to start ngrok:', errorMessage);
  console.error('\n💡 Common fixes:');
  console.error('   1. npm run dev:stop');
  console.error('   2. https://dashboard.ngrok.com/tunnels/agents → Stop old agent');
  console.error('   3. Check firewall / VPN / internet access to ngrok.com');
  console.error('   4. Verify NGROK_AUTHTOKEN in .env.development');
  console.error('   5. Run local-only: npm run dev:local\n');
}

const portBusy = await isPortInUse(PORT);
if (portBusy) {
  console.log(`\n⚠️  Port ${PORT} is already in use — server appears to be running.`);
  console.log('   ngrok will attach to the existing server (no second instance).\n');
} else {
  console.log(`\n🚀 Will start API server on port ${PORT}\n`);
}

/** @type {{ url: () => string; close: () => Promise<void>; reused?: boolean } | null} */
let listener = null;
let usingLocalFallback = skipNgrok;

if (skipNgrok) {
  console.log('ℹ️  SKIP_NGROK — starting local server only.\n');
  writeLocalEnv();
} else {
  console.log(`🔗 Starting ngrok → localhost:${PORT} ...\n`);
  stopStaleNgrokProcesses();

  try {
    listener = await startNgrokListener();
  } catch (error) {
    const message = String(error?.message || error);

    if (ngrokRequired) {
      printNgrokFailureHelp(message);
      process.exit(1);
    }

    console.warn('⚠️  ngrok unavailable — continuing with localhost only.');
    if (isNgrokNetworkError(message)) {
      console.warn('   (network could not reach ngrok servers — firewall/VPN/ISP may block it)');
    } else if (!authtoken) {
      console.warn('   Add NGROK_AUTHTOKEN to .env.development for Expo Go tunneling.');
    }
    console.warn('   For Expo on a physical device, run `npm run ngrok` when network works.\n');
    writeLocalEnv();
    usingLocalFallback = true;
  }
}

let childEnv = {
  ...process.env,
  APP_ENV: 'development',
};

if (usingLocalFallback) {
  const localUrl = `http://localhost:${PORT}`;
  childEnv = {
    ...childEnv,
    USE_NGROK: 'false',
    LOCAL_URL: localUrl,
    BASE_URL: localUrl,
    API_URL: `${localUrl}/api`,
  };
  console.log('✅ Local development mode');
  console.log(`   LOCAL_URL:  ${localUrl}`);
  console.log(`   API_URL:    ${localUrl}/api`);
  console.log('\n📱 Same Wi‑Fi: use your PC LAN IP instead of localhost in Expo.\n');
} else {
  const publicUrl = listener.url().replace(/\/+$/, '');
  const apiUrl = `${publicUrl}/api`;
  const localUrl = `http://localhost:${PORT}`;
  const socketUrl = publicUrl.replace(/^https:/i, 'wss:').replace(/^http:/i, 'ws:');

  writeNgrokEnv(publicUrl);

  childEnv = {
    ...childEnv,
    USE_NGROK: 'true',
    LOCAL_URL: localUrl,
    NGROK_URL: publicUrl,
    BASE_URL: publicUrl,
    API_URL: apiUrl,
  };

  console.log('✅ ngrok tunnel ready');
  console.log(`   LOCAL_URL:  ${localUrl}`);
  console.log(`   BASE_URL:   ${publicUrl}`);
  console.log(`   API_URL:    ${apiUrl}`);
  console.log(`   SOCKET_URL: ${socketUrl}`);
  if (listener.reused) {
    console.log('   (reused existing cloud tunnel)');
  }
  console.log('\n📱 Point Expo Go to API_URL\n');
}

/** @type {import('node:child_process').ChildProcess | null} */
let child = null;

if (!portBusy) {
  child = spawn('npm run dev:server', {
    cwd: root,
    stdio: 'inherit',
    shell: true,
    env: childEnv,
  });
} else if (listener && !listener.reused) {
  console.log('ℹ️  Restart the existing server to load .env.ngrok.local (Ctrl+C then npm run dev).\n');
}

let shuttingDown = false;
const shutdown = async (exitCode = 0) => {
  if (shuttingDown) return;
  shuttingDown = true;
  console.log('\n🛑 Shutting down...');
  if (listener && !listener.reused) {
    try {
      await listener.close();
    } catch {
      /* ignore */
    }
    try {
      await ngrok.kill();
    } catch {
      /* ignore */
    }
  }
  if (child && !child.killed) {
    child.kill('SIGTERM');
  }
  setTimeout(() => process.exit(exitCode), 300);
};

process.on('SIGINT', () => shutdown(0));
process.on('SIGTERM', () => shutdown(0));
if (child) {
  child.on('exit', (code) => shutdown(code ?? 0));
}
