#!/usr/bin/env node
/**
 * Standalone ngrok tunnel (without starting the API server).
 * Usage: npm run ngrok
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
import ngrok from '@ngrok/ngrok';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

dotenv.config({ path: path.join(root, '.env.development') });

const PORT = Number(process.env.PORT || 8000);
const authtoken = process.env.NGROK_AUTHTOKEN?.trim();

if (!authtoken) {
  console.error('\n❌ NGROK_AUTHTOKEN is missing. Add it to .env.development\n');
  process.exit(1);
}

const forwardOptions = { addr: PORT, authtoken };
const staticDomain = process.env.NGROK_DOMAIN?.trim();
if (staticDomain) forwardOptions.domain = staticDomain;

console.log(`\n🔗 ngrok http ${PORT}\n`);

const listener = await ngrok.forward(forwardOptions);
const publicUrl = listener.url().replace(/\/+$/, '');
const apiUrl = `${publicUrl}/api`;
const localUrl = `http://localhost:${PORT}`;

const ngrokEnvPath = path.join(root, '.env.ngrok.local');
fs.writeFileSync(
  ngrokEnvPath,
  [
    '# Auto-generated by npm run ngrok',
    'APP_ENV=development',
    'USE_NGROK=true',
    `LOCAL_URL=${localUrl}`,
    `NGROK_URL=${publicUrl}`,
    `BASE_URL=${publicUrl}`,
    `API_URL=${apiUrl}`,
    '',
  ].join('\n'),
  'utf8',
);

console.log('✅ Tunnel active (Ctrl+C to stop)');
console.log(`   BASE_URL: ${publicUrl}`);
console.log(`   API_URL:  ${apiUrl}`);
console.log(`\n   Saved to .env.ngrok.local — restart the server to apply.\n`);

const shutdown = async () => {
  console.log('\n🛑 Closing ngrok tunnel...');
  await listener.close();
  process.exit(0);
};

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);

// Keep the Node process alive so the tunnel stays open.
setInterval(() => {}, 1 << 30);
